config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root 'home#index'

  get 'about' => 'home#about'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/github", as: :sign_in_with_github
  get "/auth/linkedin", as: :sign_in_with_linkedin
  get "/auth/:provider/callback" => "callbacks#index"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :users, only: [:new, :create, :edit, :update]

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  get       "/favourites"     => "favourites#index",   as: :user_favourite_posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

# This validates that the comment isn't blank and that the comment hasn't been added before
validates :body, {presence: {message: "can't be blank!"}, uniqueness: {message: "already exists, please try a different one!"}}

  def user_full_name
    user ? user.full_name : ""
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_and_authorize_comment, only: :destroy

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find params[:post_id]
    @comment = Comment.create comment_params
    @comment.post = @post
    @user = current_user
    @comment.user = @user
    respond_to do |format|
      if @comment.save
        if @comment.user != @post.user
          CommentsMailer.notify_post_owner(@comment).deliver_later
        end
        format.html { redirect_to post_path(@post), notice: "Comment added successfully" }
        format.js { render :create_success }
      else
        format.html { render "/posts/show" }
        format.js { render :create_failure }
      end
    end
  end


  def show
    @comment = Comment.find(params[:id])
  end

  def index
    @comments = Comment.all
  end

  def edit
  end

  def update
    if @comment.update comment_params
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js   { render }
      end
    else
      render :edit
    end
  end

  def destroy
  @post = Post.find params[:post_id]
  @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js { render }
    end
  end



private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_post
    @post = Post.find params[:post_id]
  end

  def find_comment
    @comment = Comment.find params[:id]
  end

  def find_and_authorize_comment
    @comment = @post.comments.find params[:id]
    head :unauthorized unless (can? :destroy, @comment) || (can? :manage, @comment)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id='<%= dom_id(comment) %>' class="well" style="<%= style if defined?(style) %>">
  <p>Added by: <%= comment.user_full_name %></p>
  <p><%= comment.body %></p>
  <% if can? :edit, comment %>
  <%= link_to edit_post_comment_path(@post, comment),
                        remote: true,
                        data: {toggle: "modal", target: "#edit-comment"},
                        class: "btn btn-success btn-xs" do %>
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit Comment
        <% end %>


  <% end %>
  <% if can? :destroy, comment %>
  <%= link_to post_comment_path(@post, comment),
                        method: :delete,
                        remote: true,
                        data: {confirm: "Are you sure you want to delete this comment?"},
                        class: "btn btn-primary btn-xs" do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i> Delete Comment
          <% end %>
  <% end %>
</div>

app/views/comments/_comments.html.erb
<% comments.order("created_at asc").each do |comment| %>
  <%= render "/comments/comment", comment: comment %>
<% end %>

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= simple_form_for [@post, comment], remote: true do |f| %>
  <div>
    <%= f.input :body, label: false, placeholder:"Add Your Comment Here...", input_html: { class:"form-control", rows: 4 } %>
  </div>
  <div>
  <%= f.submit "Add comment", class:"btn btn-success btn-lg" %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <% end %>

app/views/comments/_modal_form.html.erb
<%= @comment.errors.full_messages.join(", ") %>
<%= simple_form_for [@post, @comment], remote: true do |f|  %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Comment</h4>
      </div>
      <div class="modal-body">
        <%= f.input :body, label: false, placeholder:"Add Your Comment Here...", input_html: { class:"form-control", rows: 4 } %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/create_failure.js.erb
$("#comment-form").html("<%= j render 'form' %>");

app/views/comments/create_success.js.erb
$("#comments").append("<%= j render '/comments/comment', comment: @comment, style: 'display: none' %>");
$("#comment-form").html("<%= j render 'form', comment: Comment.new %>");
$("#<%= dom_id(@comment) %>").slideDown(700);

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(700, function(){ $(this).remove(); });

app/views/comments/edit.html.erb
<h1>Edit an existing comment</h1>
<%= render "form" %>

app/views/comments/edit.js.erb
$("#edit-comment").html("<%= j render 'modal_form' %>");

app/views/comments/index.html.erb
<h1>All Comments</h1>

<% @comments.each do |comment|  %>
  <div>
    <h2><%= link_to comment.body, comment_path(comment) %></h2>
    <p><%= comment.body %></p>
    <hr>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>Add a new comment</h1>
<%= render "form" %>

app/views/comments/show.html.erb
<p><%= @comment.body %></p>
<p><%= @comment.created_at %></p>
<% if can? :edit, @comment %>
<%= link_to "Edit", edit_comment_path(@comment) %>
<% end %>
<% if can? :destroy, @comment %>
<%= link_to "Delete", comment_path(@comment),
                      method: :delete,
                      data: {confirm: "Are you sure you want to delete this comment?"} %>
<% end %>

app/views/comments/update.js.erb
$("#edit-comment").html("<%= j render 'modal_form' %>");
$("#comments").html("<%= j render 'comments', comments: @post.comments %>");
$("#edit-comment").modal("hide")