config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root 'home#index'

  get 'about' => 'home#about'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/github", as: :sign_in_with_github
  get "/auth/linkedin", as: :sign_in_with_linkedin
  get "/auth/:provider/callback" => "callbacks#index"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :users, only: [:new, :create, :edit, :update]

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  get       "/favourites"     => "favourites#index",   as: :user_favourite_posts

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessor :current_password


  has_many :posts,    dependent: :nullify
  has_many :comments, dependent: :nullify

  has_many :favourites, dependent: :destroy
  has_many :favourited_posts, through: :favourites, source: :post

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
            unless:   :from_omniauth?

  serialize :twitter_raw_data

  def full_name
    "#{first_name} #{last_name}"
  end

  def generate_password_reset_data
    generate_password_reset_token
    self.password_reset_requested_at = Time.now
    save
  end

  def password_reset_expired?
    password_reset_requested_at <= 60.minutes.ago
  end

  private

  def generate_password_reset_token
    begin
      self.password_reset_token = SecureRandom.hex(32)
    end while User.exists?(password_reset_token: self.password_reset_token)
  end

  def from_omniauth?
    uid.present? && provider.present?
  end

  def self.find_from_omniauth(omniauth_data)
  User.where(provider: omniauth_data["provider"],
             uid:      omniauth_data["uid"]).first
           end

  def self.create_from_omniauth(omniauth_data)
    full_name = omniauth_data["info"]["name"].split
    User.create(uid:                      omniauth_data["uid"],
                provider:                 omniauth_data["provider"],
                first_name:               full_name[0],
                last_name:                full_name[1],
                twitter_consumer_token:   omniauth_data["credentials"]["token"],
                twitter_consumer_secret:  omniauth_data["credentials"]["secret"],
                twitter_raw_data:         omniauth_data,
                password:                 SecureRandom.hex(16)
                )
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Account Created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      redirect_to root_path, notice: "Profile updated successfully!"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :current_password, :password, :password_confirmation)
  end

  def find_user
    @user = User.find params[:id]
  end

end


# TODO ADD PASSWORD RESET

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :current_password %>
    <%= f.password_field :current_password %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>


  <div>
  <%= f.submit "Update profile" %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10 col-xs-12">
  <h1 class="text-center">Create an account</h1>
  <br>
  <div class="text-center">
    <a href="<%= sign_in_with_github_path %>" class="btn btn-sm btn-info"><i class="fa fa-2x fa-github" aria-hidden="true"></i> Sign up with GitHub</a>
    <a href="<%= sign_in_with_twitter_path %>" class="btn btn-sm btn-info"><i class="fa fa-2x fa-twitter" aria-hidden="true"></i> Sign up with Twitter</a>
    <a href="<%= sign_in_with_linkedin_path %>" class="btn btn-sm btn-info"><i class="fa fa-2x fa-linkedin-square" aria-hidden="true"></i> Sign up with Linkedin</a>
  </div>
  <br>
  <hr>
  <h3 class="text-center"> Or Sign Up With Your Email</h3>
  <%= simple_form_for @user do |f|%>
  <div class="input-group">
      <span class="input-group-addon">
          <i class="fa fa-user fa-2x" aria-hidden="true"></i>
      </span>
    <%= f.input :first_name, label: false, placeholder: "First Name", input_html: { class:"form-control form-with-icon input-lg" }, label_html: { class:"input-lg" } %>
  </div>
  <div class="input-group">
      <span class="input-group-addon">
          <i class="fa fa-user fa-2x" aria-hidden="true"></i>
      </span>
    <%= f.input :last_name, label: false, placeholder: "Last Name", input_html: { class:"form-control form-with-icon input-lg" }, label_html: { class:"input-lg" } %>
  </div>
  <div class="input-group">
      <span class="input-group-addon">
          <i class="fa fa-envelope-o fa-2x" aria-hidden="true"></i>
      </span>
      <%= f.input :email, label: false, placeholder: "Email", input_html: { class:"form-control form-with-icon input-lg" }, label_html: { class:"input-lg" }%>
  </div>
  <div class="input-group">
      <span class="input-group-addon">
          <i class="fa fa-key fa-2x" aria-hidden="true"></i>
      </span>
    <%= f.input :password, label: false, placeholder: "Password", input_html: { class:"form-control form-with-icon input-lg" }, label_html: { class:"input-lg" } %>
  </div>
  <div class="input-group">
      <span class="input-group-addon">
          <i class="fa fa-key fa-2x" aria-hidden="true"></i>
      </span>
    <%= f.input :password_confirmation, label: false, placeholder: "Password Confirmation", input_html: { class:"form-with-icon form-control input-lg" }, label_html: { class:"input-lg" } %>
  </div>

  <br>
  <div>
  <%= f.submit "Create account!", class:"btn btn-success btn-lg center-block"%>
  </div>
  <% end %>
  <br>
  <br>
  <br>
  <br>

</div>