config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root 'home#index'

  get 'about' => 'home#about'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/github", as: :sign_in_with_github
  get "/auth/linkedin", as: :sign_in_with_linkedin
  get "/auth/:provider/callback" => "callbacks#index"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :users, only: [:new, :create, :edit, :update]

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  get       "/favourites"     => "favourites#index",   as: :user_favourite_posts

end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><i class="fa fa-leaf" aria-hidden="true" style="color: #18BC9C"></i> LeBlog</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(about_path) %>"><a href="<%= about_path %>">About</a></li>
        <li class="<%= 'active' if current_page?(posts_path) %>"><a href="<%= posts_path %>">View Posts</a></li>
        <li class="<%= 'active' if current_page?(new_post_path) %>"><a href="<%= new_post_path %>">Add New Post</a></li>
      </ul>



      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="navbar-text"><%= current_user.first_name %></li>
          <li class="<%= 'active' if current_page?(user_favourite_posts_path) %>">
            <a href="<%= user_favourite_posts_path %>">
              Favourites
              <% if current_user.favourites.length > 0 %>
                <span class="label label-success">
                  <%= current_user.favourites.length %>
                </span>
              <% end %>
            </a>
          </li>

          <li><%= link_to "Logout", sessions_path, method: :delete,
                      data: {confirm: "are you sure you want to log out?"}%></li>
        <% else %>
          <li class="<%= 'active' if current_page?(new_session_path) %>"><a href="<%= new_session_path %>">Login</a></li>
          <li class="<%= 'active' if current_page?(new_user_path) %>"><a href="<%= new_user_path %>">Sign Up</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>