config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root 'home#index'

  get 'about' => 'home#about'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/github", as: :sign_in_with_github
  get "/auth/linkedin", as: :sign_in_with_linkedin
  get "/auth/:provider/callback" => "callbacks#index"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :users, only: [:new, :create, :edit, :update]

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  get       "/favourites"     => "favourites#index",   as: :user_favourite_posts

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.order("created_at desc" ).limit(5)
    render layout: "special_layout"
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>About LeBlog</h1>
<p>This blog was built by Cristian using Ruby on Rails!</p>
<img src="https://pbs.twimg.com/profile_images/378800000799475043/1d250856b575d2aab96fca694fc50c1c_400x400.jpeg" style="border-radius:50px; width:200px" >

app/views/home/index.html.erb
<header class="intro-header front-page-image">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1 class="blog-title"><i class="fa fa-leaf" aria-hidden="true" style="color: #18BC9C"></i>LeBlog</h1>
                    <hr class="small">
                    <span class="blog-subtitle">One dream, one team &amp; one blog to post them all</span>
                </div>
            </div>
        </div>
    </div>
</header>



<div class="container">
  <div class="row">
    <div class="col-lg-offset-1 col-lg-10 col-md-offset-1 col-sm-offset-1 col-sm-10 col-xs-12">
        <% @posts.each do |post| %>
        <div class="panel panel-info">
          <div class="panel-heading panel-title-gradient">
            <h2 class="panel-title lead"><%= link_to post.title, post_path(post) %></h2>
            <% if post.category %>
            <p class="pull-right label label-default">Category: <%= post.category.title.titleize %> </p>
            <% end %>
            <p>Posted by <%= post.user_full_name %> on <span class="post-meta"> <%= post.created_at.strftime("%b %d, %Y") %></span></p>
          </div>
          <div class="panel-body">
            <%= markdown post.body_snippet_extended %>
            <br>
          </div>
          <div class="panel-footer">
          </div>
        </div>
        <% end %>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-md-offset-5 col-md-6 col-xs-offset-5">
      <a href="<%= posts_path %>" class="btn btn-primary btn-lg">Read More Posts...</a>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>
</div>